---
version: '2'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.60
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14269:14269"
      - "9411:9411"
    container_name: jaeger-collector
    hostname: jaeger-collector
    restart: unless-stopped
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - ES_PASSWORD=${ELASTIC_PASSWORD}
      - ES_USERNAME=elastic
      - COLLECTOR_ZIPKIN_HOST_PORT:9411
    networks:
    - docker-elk
networks:
  docker-elk:
    name: docker-elk_elk 
    external: true
